// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trmsyoidbqpbabzhycsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRybXN5b2lkYnFwYmFiemh5Y3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTMwODgsImV4cCI6MjA1NzM4OTA4OH0.SORmqv-D1NazhU32A6EoVKH6V6Gy5rkoCErNeXal6zA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);